name: Generate Language Stats Card

on:
  schedule:
    - cron: '0 */6 * * *'   # প্রতি ৬ ঘণ্টা পর পর auto-update
  workflow_dispatch:         # চাইলে manually "Run workflow" থেকেও চালানো যাবে

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate cards
        uses: vn7n24fzkq5/github-profile-summary-cards@release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: souravsahapartho
          theme: github_dark
          card_width: 500
